config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "toppages#index"

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :results, only: [:index, :create]
  resources :users, only: [:index, :show, :create]
end

app/views/toppages/partial/login/_game.html.erb
<div class="l-flex">
  <% prefix = "game[user_hands][]"%>
  <%= form_with(url: results_path , local: true) do |f| %>
  <div class="l-flex">
    <% player_cards.each_with_index do |card, num| %>
    <div class="image-box">
      <%= image_tag "#{card.type}/#{card.id}.png", {id: "card-#{num + 1}",class: "image-size toppage-cards",size: "100x150" }%>
      <div class="hold-text display-none" id=<%="card-#{num + 1}-text-hold"%>>Hold</div>
      <%= f.hidden_field "#{prefix}is_hold",{class: "display-none",id:"card-#{num + 1}-checkbox",value:card.is_hold} %>
      <%= f.hidden_field "#{prefix}type" ,value: card.type %>
      <%= f.hidden_field "#{prefix}id",value: card.id %>
    </div>
    <% end %>
  </div>
  <div class="l-text-center">
    <%= f.submit 'play', class: 'button button-secondary',id: "play-poker" %>
  </div>
  <% end %>
</div>

app/views/toppages/partial/login/_index.html.erb
<h1 class="font-size-logo">Start</h1>
<% texts = ["You play against the cpu by the strength of your hand.",
  "Click on the card to hold it",
  "You can only exchange your card once.",
  "Press the Play button",
  "If the hands are the same, the cpu wins"]%>
<ol>
  <% texts.each{|text| %>
  <li class="font-size-list"><%=text %></li>
  <% } %>
</ol>
<div class="TB-micro-padding"></div>
<%= render 'toppages/partial/login/game',{result:@result,player_cards:@player_cards} %>