config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "toppages#index"

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :results, only: [:index, :create]
  resources :users, only: [:index, :show, :create]
end

app/views/layouts/_flash.html.erb
<div class="notifications">
  <% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header class="l-header">
  <h1 class="font-size-logo">
    <a href="/"><%= title %></a>
  </h1>

  <nav class="pc-nav">
    <ul>
      <% if logged_in? %>
      <li class="font-size-sp"><%= link_to "users", users_path %></li>
      <li class="font-size-sp"><%= link_to "#{current_user.name}", current_user %></li>
      <li class="font-size-sp"><%= link_to 'logout', logout_path, method: :delete %></li>
      <% else %>
      <li class="font-size-sp"><%= link_to 'signup', signup_path %></li>
      <li class="font-size-sp"><%= link_to "login", login_path %></li>
      <% end %>
    </ul>
  </nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>simplePoker</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
  <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>

  <!-- font-awesome -->
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
    integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <!-- googlefont -->
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,400italic,700,700italic,900,900italic"
    rel="stylesheet">
  <meta name="google-site-verification" content="xp6H7IWI1I6ayxbxHgkKtiaiKNLNPBCBr5uSI70RqkM" />
</head>

<body>
  <%= render "layouts/header",{title:"simplePoker"} %>
  <%= render 'layouts/flash' %>
  <div class="TB-middle-padding"></div>
  <%= yield %>

</body>

</html>